components:
- name: hello-bucket
  type: bucket
  website: true
  functions:
  - name: hello-get
    path: whatever
- name: hello-get
  type: function
  iam:
    permissions:
    - "logs:*"
    - "dynamodb:*" # required for event mapping
    - "sqs:*" # required for event mapping
  api:
    method: GET
- name: hello-post
  type: function
  iam:
    permissions:
    - "logs:*"
  api:
    method: POST
- type: queue
  name: hello-queue
  function: hello-get
  batch: 1
- name: hello-timer
  type: timer
  function: hello-get
  rate: "1 hour"
  payload: 
    hello: world
- name: hello-table
  type: table
  fields:
  - name: my-hash
    type: string
    primary: true
  - name: my-string
    type: string
    index: true
  function: hello-get


