components:
- name: hello-bucket
  type: bucket
  event:
    type: FOOBAR # TEMP
  website: true
  actions:
  - name: hello-get
    path: whatever
- name: hello-get
  type: function
  concurrency: 1000 # TEMP
  iam:
    permissions:
    - "logs:*"
    - "dynamodb:*" # required for event mapping
    - "sqs:*" # required for event mapping
  api:
    method: GET
- name: hello-post
  type: function
  iam:
    permissions:
    - "logs:*"
  api:
    method: POST
- type: queue
  name: hello-queue
  action:
    name: hello-get
    batch: 1
- name: hello-timer
  type: timer
  action:
    name: hello-get
  rate: "1 hour"
  payload: 
    hello: world
- name: hello-table
  type: table
  stream:
    type: FOOBAR # TEMP
  fields:
  - name: my-hash
    type: string
    primary: true
  - name: my-string
    type: string
    index: true
  action:
    name: hello-get


